name: terratests-port-prod-suite

on:
  workflow_dispatch:

jobs:
  setup-tests:
    name: Setup PROD DIGP Tests
    runs-on: ubuntu-latest
    env:
      TF_VAR_equinix_client_id: ${{ secrets.EQUINIX_CLIENT_ID }}
      TF_VAR_equinix_client_secret: ${{ secrets.EQUINIX_CLIENT_SECRET }}
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID}}
      TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET}}
      TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID}}
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
      GOOGLE_SERVICE_KEYS: ${{ secrets.GOOGLE_SERVICE_KEYS }}
      TEST_DATA_PROD_PORT_2_ALIBABA_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_ALIBABA_CONNECTION }}
      TEST_DATA_PROD_PORT_2_AWS_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_AWS_CONNECTION }}
      TEST_DATA_PROD_PORT_2_AZURE_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_AZURE_CONNECTION }}
      TEST_DATA_PROD_PORT_2_GOOGLE_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_GOOGLE_CONNECTION }}
      TEST_DATA_PROD_PORT_2_ORACLE_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_ORACLE_CONNECTION }}
      TEST_DATA_PROD_PORT_2_PORT_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_PORT_CONNECTION }}
      TEST_DATA_PROD_PORT_2_PRIVATE_SERVICE_PROFILE_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_PRIVATE_SERVICE_PROFILE_CONNECTION }}
      TEST_DATA_PROD_PORT_2_WAN_CONNECTION: ${{ secrets.TEST_DATA_PROD_PORT_2_WAN_CONNECTION }}
    outputs:
      message: ${{ steps.slack_message.outputs.message }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/run-test
        continue-on-error: true
        with:
          test-dir: ./tests/prod/cloud-router
          test-filter: TestPortDIGP

      - name: Run Sweepers
        run: |
          go run ./tests/sweepers/cmd

      - uses: ./.github/actions/process-report
        with:
          slack-token: ${{ secrets.SLACK_ACCESS_TOKEN }}
