name: terratests-uat-suite

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup-tests:
    name: Setup UAT Tests
    runs-on: ubuntu-latest
    env:
      EQUINIX_API_ENDPOINT: "https://uatapi.equinix.com"
      TEST_DATA_UAT_PORT_2_PORT_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_PORT_CONNECTION}}
      TEST_DATA_UAT_PORT_2_AZURE_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_AZURE_CONNECTION}}
      TEST_DATA_UAT_PORT_2_AWS_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_AWS_CONNECTION}}
      TEST_DATA_UAT_PORT_2_IBM2_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_IBM2_CONNECTION}}
      TEST_DATA_UAT_PORT_2_ALIBABA_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_ALIBABA_CONNECTION}}
      TEST_DATA_UAT_CLOUD_ROUTER_2_PORT_CONNECTION: ${{secrets.TEST_DATA_UAT_CLOUD_ROUTER_2_PORT_CONNECTION}}
      TEST_DATA_UAT_PORT_2_PUBLIC_SERVICE_PROFILE_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_PUBLIC_SERVICE_PROFILE_CONNECTION}}
      TEST_DATA_UAT_PORT_2_PRIVATE_SERVICE_PROFILE_CONNECTION: ${{secrets.TEST_DATA_UAT_PORT_2_PRIVATE_SERVICE_PROFILE_CONNECTION}}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
        id: go

      - name: Get dependencies
        run: |
              go mod download
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Setup Variables Files
        run: |
          for list in ./examples/*; do
              if [[ "$list" == *"port-2-port-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_PORT_CONNECTION >> "$list/terraform.tfvars.json"
              elif [[ "$list" == *"port-2-ibm2-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_IBM2_CONNECTION >> "$list/terraform.tfvars.json"
              elif [[ "$list" == *"port-2-alibaba-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_ALIBABA_CONNECTION >> "$list/terraform.tfvars.json"
              elif [[ "$list" == *"port-2-public-service-profile-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_PUBLIC_SERVICE_PROFILE_CONNECTION >> "$list/terraform.tfvars.json"
              elif [[ "$list" == *"port-2-private-service-profile-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_PRIVATE_SERVICE_PROFILE_CONNECTION >> "$list/terraform.tfvars.json"
              fi     
          done
          for list in ./tests/uat/*; do
              if [[ "$list" == *"port-2-azure-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_AZURE_CONNECTION >> "$list/terraform.tfvars.json"
              elif [[ "$list" == *"port-2-aws-connection"* ]]; then
                  echo $TEST_DATA_UAT_PORT_2_AWS_CONNECTION >> "$list/terraform.tfvars.json"
              fi
              
          done
      - name: Run Go Tests
        run:
          go test ./tests/uat -v -coverprofile coverage_uat_modules.txt -covermode=atomic -count 1 -parallel 8 -timeout 180m

      - name: Upload test coverage to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage_uat_modules.txt